### ISSUE TITLE
Creating a Kinesis stream without enhancedMetrics enabled causes provider to crash

### ISSUE THREAD

**Issue by jonnybell895** [crossplane-contrib/provider-aws#1246]
### What happened?
When creating a Kinesis stream without enhanced metrics, the provider crashes with an index out of range error:
```
panic: runtime error: index out of range [0] with length 0
goroutine 3395 [running]:
github.com/crossplane/provider-aws/pkg/controller/kinesis/stream.(*updater).isUpToDate(0xc0009e3fd0, 0xc001ffa6c0, 0xc0009e3ed0)
    /home/runner/work/provider-aws/provider-aws/pkg/controller/kinesis/stream/setup.go:136 +0x27a
github.com/crossplane/provider-aws/pkg/controller/kinesis/stream.(*external).Observe(0xc0028a8540, {0x5cb1c80, 0xc0023fe300}, {0x5d741d8, 0xc001ffa6c0})
    /home/runner/work/provider-aws/provider-aws/pkg/controller/kinesis/stream/zz_controller.go:91 +0x2b4
github.com/crossplane/crossplane-runtime/pkg/reconciler/managed.(*Reconciler).Reconcile(0xc0004cb760, {0x5cb1cb8, 0xc001cad4a0}, {{{0x0, 0x0}, {0xc002d18ba0, 0x20}}})
    /home/runner/work/provider-aws/provider-aws/vendor/github.com/crossplane/crossplane-runtime/pkg/reconciler/managed/reconciler.go:758 +0x22eb
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc0004cb810, {0x5cb1cb8, 0xc001cad470}, {{{0x0, 0x5126c80}, {0xc002d18ba0, 0x413a94}}})
    /home/runner/work/provider-aws/provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:114 +0x26f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0004cb810, {0x5cb1c10, 0xc000b454c0}, {0x4cdbea0, 0xc001d90420})
    /home/runner/work/provider-aws/provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:311 +0x33e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0004cb810, {0x5cb1c10, 0xc000b454c0})
    /home/runner/work/provider-aws/provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
    /home/runner/work/provider-aws/provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
    /home/runner/work/provider-aws/provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:223 +0x357
```
The AWS resource creates successfully but the provider panics when checking if the resource is up-to-date, therefore it never moves to a ready state.

I believe this is caused by an assumption that there is at least one metric defined when the zero-index is referenced here:
https://github.com/crossplane/provider-aws/blob/98b12be47fff21716d44a1f319c4e1d81c043b05/pkg/controller/kinesis/stream/setup.go#L136

### How can we reproduce it?
Creating a simple Stream with the [required fields](https://doc.crds.dev/github.com/crossplane/provider-aws/kinesis.aws.crossplane.io/Stream/v1alpha1@v0.25.0) but without setting `enhancedMetrics` in the manifest should reproduce the issue.

### What environment did it happen in?
Crossplane version: 1.6.4
Kubernetes version: 1.21

**Comment by tkaesserfm** [comment]
I'm experiencing this as well
